# Generated by Django 6.1.1 on 2026-09-27 09:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('address', models.TextField(blank=True, default='')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=50)),
                ('secondary_phone', models.CharField(blank=True, default='', max_length=50)),
                ('preferred_contact_channel', models.CharField(blank=True, default='App push', max_length=50)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('saved_payment_method', models.CharField(blank=True, default='CREDIT_CARD', max_length=50)),
                ('communication_preferences', models.CharField(blank=True, default='ALL', max_length=100)),
                ('employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('specialization', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('date_joined_company', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_profiles', to='garage.vehicle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
