# Generated by Django 6.1.1 on 2026-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
